# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tigermeet.space documentation
email: ericdudley@email.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation for tigermeet.space a social media application for RIT students.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ericdudley.github.io/tigermeet/" # the base hostname & protocol for your site
twitter_username: tigermeetspace
github_username:  ericdudley

# Build settings
markdown: kramdown
